### PR TITLE
update outdated links to sensible new targets

### PR DESCRIPTION
**Pull request by katrinleinweber**

### CODE REVIEW

**Comment by rprouse** [comment]
Thanks. This solution needs updating for at least C#. Do you think it makes sense to do the work, split it up into language tracks, or maybe switch to Visual Studio Code?

**Comment by katrinleinweber** [comment]
What exactly do you mean with "solution"?

I haven't looked into other files besides the `ReadMe`, but was just browsing for an equivalend of [JonMCalder's exercism RStudio package](https://github.com/jonmcalder/exercism) for Python and one of its IDEs. I'm interested in working through the exercism Python track. Hence I found this repo, and just noticed that a few links were broken.

**Comment by rprouse** [comment]
This project is a Visual Studio solution that allows you to work on multiple language tracks. There have been some changes to several of the language tracks, so some of the language specific projects within the solution are out of date.

**Comment by katrinleinweber** [comment]
OK, thanks for explaining! I'm sorry, but that would be out-of-scope for me.

**Pull request merged**
